- hosts: webserver
  become: true  
  tasks:
    - name: Actualizar el cache de paquetes
      apt:
        update_cache: yes

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present

    - name: Iniciar y habilitar Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copiar el archivo HTML
      copy:
        src: ./web/index.html  
        dest: /usr/share/nginx/html/index.html  
