- hosts: webserver
  tasks:
    - name: Instalar Nginx
      yum:
        name: nginx
        state: present

    - name: Iniciar Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copiar el archivo HTML
      copy:
        src: ./web/index.html
        dest: /usr/share/nginx/html/index.html
